# Generated by Django 4.1.2 on 2022-10-21 07:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.RegexValidator('[A-Za-z0-9_]', message='Ensure this value contains only letters, numbers, and underscore.')]),
        ),
    ]
